### PR TITLE
add http args

### PR DESCRIPTION
**Pull request by timwhitez**
add http args

### CODE REVIEW

**Comment by mjwhitta** [comment]
Sorry for the late response here, I don't use GitHub often. I will try to merge this tonight tho.

**Comment by mjwhitta** [comment]
Weird, I added `fixes #1` to the commit message to close the issue on gitlab and it appears to have closed the PR here... regardless, I did get the query parameters working with minimal changes. I've looked through your changes and I was curious what you were doing with the content-length stuff. Looks like, in the event of an error, you just default to a content-length of 1024? Was that intentional?

**Comment by timwhitez** [comment]
there are many times that i get content-type error, and i want to know that you have some better way to solve it. thanks

**Comment by mjwhitta** [comment]
I haven't been able to reproduce any content-type errors. If you have any samples of code, I would appreciate seeing those so I can attempt to reproduce. If this is related to your [GitLab issue](https://gitlab.com/mjwhitta/win/-/issues/2). Feel free to respond there.

**Pull request closed without merging**
